platform :ios, '8.3'

target 'iQKit-Example' do
    pod 'SVProgressHUD', '~> 2.0'
    pod 'SVWebViewController', '~> 1.0'
    pod 'NFAllocInit', '~> 1.0'
#pod 'iQKit', :path => '..'
	pod 'AIQKit', '~>0.9.4.1'
end

